### ISSUE TITLE
How are the intermediate ivan_*.npy files generated?

### ISSUE THREAD

**Issue by bhavika** [qiq208/traffic4cast_graph#1]
Hi, thank you so much for making this code available. I'm using it to understand your paper https://arxiv.org/pdf/2012.02115.pdf. 

Could you please explain how the `ivan_val.npy` and `ivan_train.npy` files were created? I can only see one reference to them in the code here - https://github.com/qiq208/traffic4cast_graph/blob/7c896708f4dfd0fb8c07c3ff634251ec06b85194/src/gnn_dataset.py#L39

Any details about those files would be much appreciated 🙏🏽

**Comment by qiq208** [comment]
Hey Bhavika,
Early on in the competition, we decided not to train on every possible 12-slice window - since we were trying to do this on free Paperspace, so only did a subset of all possible frames.
We wanted to ensure that the CNN and GNN were being trained on the same data, so these files contained the indices of the training and validation samples used in the CNN code.
You can just think of them as a 'random' subset of the training and validation dataset.

**Comment by bhavika** [comment]
That makes sense! Thank you so much @qiq208. I'm going to close this issue but if you'd like to leave it open for others' benefit, feel free to reopen.
